import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./components/Header";
import Tab from "./components/Tab";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hospital Maracaí",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Tab />
        {children}
      </body>
    </html>
  );
}
