import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hospital Maracaí",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  {/* const isAdmin = false; */ }

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* isAdmin && <Header /> */}
        {children}
      </body>
    </html>
  );
}
