import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Sidebar } from './adminComponents/sidebar';
import { ThemeProvider } from "./adminComponents/theme-provider";
import * as React from "react"
import { Suspense } from 'react';


const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='dark'>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Sidebar />
          <main className='mx-5 mt-16 sm:ml-[300px] sm:mt-3'>{children}</main>
        </ThemeProvider>

      </body>
    </html>
  );
}
